name = "aliceqi-root"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"
routes = [
  { pattern = "aliceqi.com/*", zone_name = "aliceqi.com" },
  { pattern = "www.aliceqi.com/*", zone_name = "aliceqi.com" }
]
[vars]
ENV = "production"
