name = "blackroadquantum-net"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"
routes = [
  { pattern = "blackroadquantum.net/*", zone_name = "blackroadquantum.net" },
  { pattern = "www.blackroadquantum.net/*", zone_name = "blackroadquantum.net" }
]
[vars]
ENV = "production"
