name = "blackroadinc-root"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"
routes = [
  { pattern = "blackroadinc.us/*", zone_name = "blackroadinc.us" },
  { pattern = "www.blackroadinc.us/*", zone_name = "blackroadinc.us" }
]
[vars]
ENV = "production"
