name = "blackroad-systems-root"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"
routes = [
  { pattern = "blackroad.systems/*", zone_name = "blackroad.systems" }
]
[vars]
ENV = "production"
