name = "blackroadquantum-info"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"
routes = [
  { pattern = "blackroadquantum.info/*", zone_name = "blackroadquantum.info" },
  { pattern = "www.blackroadquantum.info/*", zone_name = "blackroadquantum.info" }
]
[vars]
ENV = "production"
