name = "lucidiaqi-root"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"
routes = [
  { pattern = "lucidiaqi.com/*", zone_name = "lucidiaqi.com" },
  { pattern = "www.lucidiaqi.com/*", zone_name = "lucidiaqi.com" }
]
[vars]
ENV = "production"
